### ISSUE TITLE
跑不起来 依赖下载完运行就卡住了

### ISSUE THREAD

**Issue by fbbDirge** [ZhengKe996/WeChat-Message#1]
![image](https://user-images.githubusercontent.com/86771432/185885429-715c2ed7-caaa-4c87-9a0c-1d22909e6de7.png)

**Comment by Zhengke0110** [comment]
进入 index.ts 注释掉最后的定时消息调用
<img width="845" alt="未命名" src="https://user-images.githubusercontent.com/82481893/185885810-954e4597-970a-4ae3-a868-d50347f371cc.png">
